[DO NOT MERGE] Remove stanford renderer completely!
Stanford-Online/openedx-certificates pull request #28
Opened 2016-10-03 22:47 UTC by caesar2164

This PR needs to wait until AFTER Carnegie courses sunset (early November 2016)

2016-10-05 21:18 UTC, stvstnfrd commented
We get a big coverage bump here, as we weren't testing this one..

2016-10-05 21:27 UTC, caesar2164 commented
sad, I only get 66% now because I remove v3...

2016-10-05 21:32 UTC, stvstnfrd requested changes

2016-10-05 21:32 UTC, stvstnfrd commented on gen_cert.py
> -        if self._use_unicode_font(student_name):
You should double-check, but I think this is the final remaining reference to this method.
We should be able to remove it at this point.

2016-10-05 21:32 UTC, stvstnfrd commented on gen_cert.py
> -        if self._use_unicode_font(student_name):
And once that goes, so can `_contains_characters_above`.

2016-10-05 21:35 UTC, stvstnfrd commented
> sad, I only get 66% now because I remove v3...

Well, that PR (v3) dropped as low as 60%, so all things relative :)

2016-11-02 22:01 UTC, stvstnfrd approved these changes

2016-11-02 22:01 UTC, stvstnfrd commented
@caesar2164 Does this need rebased now?

2016-11-02 22:21 UTC, merged